### ISSUE TITLE
Flextext XSLT Transformation and saxon version

### ISSUE THREAD

**Issue by anneferger** [Exmaralda-Org/exmaralda#265] opened 2021-03-17 08:26 UTC
* Since the saxon jar change, part of the Flextext transformation does not work correctly
* the transformation transforms one .flextext file using a settings.file as a parameter and creating a result-document which is the exb, while the result string of the tranformation is just a report
* transformation happens in exmaralda/src/org/exmaralda/partitureditor/jexmaralda/convert/FlexTextConverter.java at line 89
* test file is e.g. (konnte ich nur als zip hochladen)
[KGE_1965_Lgov_transl.flextext.zip](https://github.com/Exmaralda-Org/exmaralda/files/6154675/KGE_1965_Lgov_transl.flextext.zip)
* in Oxygen, using exmaralda/src/org/exmaralda/partitureditor/jexmaralda/xsl/flextext2exb.xsl with parameter SETTINGS-FILE exmaralda/src/org/exmaralda/partitureditor/jexmaralda/xsl/selkup_flextext2exb_ltr_lit-ru.xsl produces correct output
* in PE, using the INEL Menu > INEL-specific import with the Seetings "INEL Selkup Settings (Lit. Russian as ltr; with Cyrl for st)" (which is also /org/exmaralda/partitureditor/jexmaralda/xsl/selkup_flextext2exb_ltr_lit-ru.xsl) produces the strange output, where e.g. the timeline only has one timepoint so Exmaralda can't open it
* in /home/fsnv625/Documents/Documents/exmaralda/src/org/exmaralda/partitureditor/jexmaralda/xsl/flextext2exb.xsl the variable "preprocessed-root" line 182 already misses words, but not "sentences", which is not the case in Oxygen, so I think e.g. <xsl:function name="inel:append-punct"> in line 622 doesn't work
* xsl messages can be shown in exmaralda/src/org/exmaralda/partitureditor/jexmaralda/convert/FlexTextConverter.java with         

```
List<String> warnings = ssf.getWarnings();
         System.out.println("Warnings are:");
            for (String w : warnings){
                System.out.println(w);
            }
```

but they only contain normal messages in that xsl, errors are thrown with error() which works correctly as well

**Comment by nolda** [comment] 2021-03-26 17:54
Pull request #266 should fix this issue. To test, try the following:
```
java -cp saxon9.jar net.sf.saxon.Transform KGE_1965_Lgov_transl.flextext flextext2exb.xsl SETTINGS-FILE=selkup_flextext2exb_ltr_lit-ru.xsl
```

**Comment by berndmoos** [comment] 2021-03-29 06:02
Uploaded a preview with the merged changes. Anybody from INEL wants to confirm that the issue is resolved?

**Comment by sarkipo** [comment] 2021-03-29 08:52
> Uploaded a preview with the merged changes. Anybody from INEL wants to confirm that the issue is resolved?

Hi, I'll try the preview out and let you know.

**Comment by sarkipo** [comment] 2021-03-29 09:18
> Uploaded a preview with the merged changes. Anybody from INEL wants to confirm that the issue is resolved?

Yes, the import works fine now! Thanks a lot!

**Closed as completed** 2021-03-29 09:50 UTC
Labels: Partitur Editor, INEL
