### ISSUE TITLE
(Unicode) Characters change into garbage in the active annotation

### ISSUE THREAD

**Issue by sarkipo** [Exmaralda-Org/exmaralda#124] opened 2017-10-04 15:38 UTC
Here are two sample screenshots from different machines, with the same portion of the same file being edited. In the first one the content is rendered correctly, in the second one the cyrillic letters turn into garbage (should be "царь.[SG.NOM]").

![exma-unicode_bug-1](https://user-images.githubusercontent.com/11090777/31184670-53084a52-a92a-11e7-9436-cfb112925b68.png)
![exma-unicode_bug-2](https://user-images.githubusercontent.com/11090777/31184678-5891d538-a92a-11e7-93ec-a4374e6929f9.png)

**Comment by berndmoos** [comment] 2017-10-05 10:36
To reproduce this, can you tell us:

* what the two machines are (OS)?
* which font you are using for the tier in question?

A sample EXB file would be helpful, too.

**Comment by anneferger** [comment] 2017-10-12 11:00
As far as I know, it only happens with Charis SIL font, and only if the newest version (5.000) is installed on the computer. To fix it, install the older version of Charis SIL 4.114 on the computer.


(But maybe we could still find out why it doesn't work with the newest font, because it does work in other programs (notepad etc.). I have only seen it on windows yet. )

**Comment by berndmoos** [comment] 2017-11-22 10:56
Any news on this? Can we reproduce it? I suspect it will be a bug in the font rather than in EXMARaLDA. We should close the issue if nothing further is expected to happen.

**Closed as completed by berndmoos** 2017-11-22 10:56 UTC
Labels: help wanted, Partitur Editor

**Comment by anneferger** [comment] 2017-11-22 11:25
Yes, can be closed, older version of font works fine on the three computers I saw this bug on
