### ISSUE TITLE
PE cannot open a transcript if the WAV file has time markers/regions

### ISSUE THREAD

**Issue by sarkipo** [Exmaralda-Org/exmaralda#268] opened 2021-06-08 15:19 UTC
PartiturEditor hangs while trying to open an exb. It happens when the linked WAV file has some time markers in the metadata.
(In this case the markers were created in SoundForge.)
When the markers are removed, the exb is opened without problems (try the SSI_196X_Lifestory_nar-nomarkers.wav).

SSI_196X_Lifestory_nar.exb
https://yadi.sk/d/4gynlN-KGlN4iQ
SSI_196X_Lifestory_nar.wav
https://yadi.sk/d/39Cn9bmExnNGAA
SSI_196X_Lifestory_nar-nomarkers.wav
https://yadi.sk/d/AVBdxHHyLT3R9A

NB I tried to produce a smaller working example, but it didn't cause PE to fail:
test-markers.wav
https://yadi.sk/d/qvraal5Dd_u0Hg

I am not sure, but I think I previously had files with markers opened without problems in PE.
I also know ELAN opens such files ok and even displays the markers.

**Comment by berndmoos** [comment] 2021-06-09 05:40
Thanks, I'll look into this.

**Comment by berndmoos** [comment] 2021-06-09 06:36
I can reproduce the problem with the PE on Windows with all players (JavaFX, BAS, JDS). Just opening the sound files with the players (i.e. outside PE) works fine. The problem seems to be in my version of ELANWAVHeader, which is part of the code for reading the waveform data.

**Comment by berndmoos** [comment] 2021-06-09 07:23
I think I fixed this (by transferring the current version of WAVHeader from ELAN to EXMARaLDA). @sarkipo : can you please check if it works with the latest preview? I only uploaded Windows so far, please let me know if you need MAC OS.

**Comment by sarkipo** [comment] 2021-06-09 10:51
> @sarkipo : can you please check if it works with the latest preview? I only uploaded Windows so far, please let me know if you need MAC OS.

Thanks, that's great, works fine now!

**Comment by berndmoos** [comment] 2021-06-10 13:20
Fixed, it seems.

**Closed as completed by berndmoos** 2021-06-10 13:20 UTC
Labels: bug, Partitur Editor, EXAKT, OrthoNormal, FOLKER
